language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

before_install:
  #This should solve problem installing Perl's DB_File & GraphViz
  - sudo apt-get update -qq
  -  "sudo apt-get install libdb-dev libxml2-dev 2>&1 | tail -n 4"
