language: perl
perl: 5.20

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install libdb-dev libxml2-dev libxslt1-dev texlive texlive-fonts-extra texlive-latex-extra texlive-lang-cyrillic

install:
 - cpanm --installdeps .
 - cpanm Marpa::R2
 - cpanm Test::LeakTrace

script:
 - perl Makefile.PL
 - make
 - git clone https://github.com/KWARC/sTeX
 - export STEXSTYDIR=`pwd`/sTeX/sty
 - make test
